### ISSUE TITLE
poder modificar el volumen de los tonos independientemente

### ISSUE THREAD

**Issue by yagui** [IIBM/sphere-training#12]
El tono de 8kHz se termina escuchando mucho más fuerte que el de 1 kHz, ya sea por el parlante o por la computadora.
Sería bueno poder reducir el volumen de un tono, en forma independiente del otro, para poder ajustar el nivel final con el amplificador del parlante

**Comment by yagui** [comment]
modifique las bibliotecas de generacion de sonido, falta modificar training.py para poder utilizarlo desde el archivo de configuracion

**Comment by alfredoivan** [comment]
falta agregar las mismas opciones que existen en Glade GTK para la otra interfaz GUI, la hecha en TKinter
