### ISSUE TITLE
Se congela la ventana de tracking

### ISSUE THREAD

**Issue by yagui** [IIBM/sphere-training#16]
Durante el entrenamiento, la ventana que muestra el tracking de la camara se congela, el software sigue funcionando y se puede ejectura el comando salir, aunque el proceso de la camara, (probablemente spherevideotracking) no responde y hay que matar todos los procesos python.
Esto empezó a suceder a partir de los cambios posteriores al commit https://github.com/IIBM/sphere-training/commit/703c7d505f7792a55c8c0c47c1e60c7fa450a06d

**Comment by alfredoivan** [comment]
_

**Comment by alfredoivan** [comment]
Muy probablemente asociado a grabación de video en sphereVideoDetection . Falta verificar in situ
Puede estar asociado también a grabación de audio.

**Comment by alfredoivan** [comment]
Es un error aleatorio, no se sabe qué lo ocasiona (posiblemente bufferear frames en memoria y luego grabar en disco minimice las ocurrencias de este error, pero igualmente siga existiendo).

Posiblemente asociado a un capture de CV2 mal hecho, un frame vacío, y demás.
(agregar condicionales para determinar si un frame está vacío)

**Comment by yagui** [comment]
los cambios realizados parecen haber solucionado el problema, se cierra el issue
