### ISSUE TITLE
grabar sonido y video cuando se pulsa "start training"

### ISSUE THREAD

**Issue by alfredoivan** [IIBM/sphere-training#8]
y no antes, como actualmente.

**Comment by alfredoivan** [comment]
(cuando se pausa el entrenamiento, dejar de grabar audio, cuando se reanuda continuar)
ídem video

**Comment by alfredoivan** [comment]
En cada "trial start" hay que poner un fotograma rojo (o de algún color) en el video para poder después separarlo en sus componentes trials.

Cuando se pausa y reanuda, seguir grabando video y audio?

**Comment by yagui** [comment]
Durante la pausa es mejor continuar grabando, ya que el sistema de registro de spikes continuará grabando y puede haber algo útil.
